# auto-generated gallery items: (filename, category, caption)
FILTERS=[('all','All'),('cards','Cards'),('stationery','Stationery'),('brochures','Brochures & Flyers'),('idcards','ID & Lanyards'),('signage','Signage'),('stickers','Stickers & Labels'),('gifting','Gifting'),('books','Books')]
GALLERY=[
  ('premium-business-cards.jpg','cards','Premium business cards'),
  ('business-card-printing-in-chennai.jpg','cards','Multi-colour visiting cards'),
  ('creative-busness-card-design.jpg','cards','Creative card design'),
  ('nfc-business-card-in-chennai.jpg','cards','NFC smart cards'),
  ('wedding-card-printing-chennai.jpg','cards','Wedding invitations'),
  ('letterhead-printing-chennai.jpg','stationery','Corporate letterheads'),
  ('imported-paper-letterhead-printing.jpg','stationery','Imported-paper letterheads'),
  ('envelope-printing-chennai.jpg','stationery','Branded envelopes'),
  ('bill-book-printing-services.jpg','stationery','NCR bill books'),
  ('corporate-identity-design.jpg','stationery','Corporate identity set'),
  ('brochure-printing-in-chennai.jpg','brochures','Tri-fold brochures'),
  ('brochure-designer-chennai.jpg','brochures','Brochure design'),
  ('best-flyer-printing-chennai.jpg','brochures','Full-colour flyers'),
  ('flyer-design-chennai.jpg','brochures','Flyer design'),
  ('booklet-printing-chennai.jpg','brochures','Saddle-stitched booklets'),
  ('id-card-printing-service-in-chennai.jpg','idcards','PVC ID cards'),
  ('office-id-card-printing-in-chennai.jpg','idcards','Office ID cards'),
  ('Lanyard-Printing.jpg','idcards','Custom lanyards'),
  ('id-card-design-chennai.jpg','idcards','ID card design'),
  ('Rollup-Standee-Design-and-Printing-in-Chennai.jpg','signage','Roll-up standees'),
  ('standee-design-chennai-1.jpg','signage','Standee design'),
  ('flex-printing-services-in-chennai.jpg','signage','Flex banners'),
  ('welcome-boards.jpg','signage','Welcome boards'),
  ('sticker-printing-chennai.jpg','stickers','Custom stickers'),
  ('Product-label-printing-in-chennai.jpg','stickers','Product labels'),
  ('product-sticker-printing-chennai.jpg','stickers','Product stickers'),
  ('cd-sticker-printing-chennai.jpg','stickers','CD / DVD stickers'),
  ('clothing-stickers-and-labels-printing.jpg','stickers','Clothing labels'),
  ('mug-printing-chennai.jpg','gifting','Photo mugs'),
  ('water-bottle-printing-services.jpg','gifting','Branded bottles'),
  ('keychain-printing-services.jpg','gifting','Custom keychains'),
  ('book-printing-chennai.jpg','books','Perfect-bound books'),
  ('hotcase-book-binding.jpg','books','Hardcase binding'),
  ('book-design-chennai.jpg','books','Book & cover design'),
]
