# -*- coding: utf-8 -*-
"""Service catalogue. Each entry: slug, name, category, price, tagline,
paragraphs (list), specs (list of [label, value]), included (list)."""

INCLUDED_DEFAULT = [
    "Free artwork check by our studio",
    "Digital proof before we print",
    "Colour sampling during the run",
    "Delivery across Vellore town",
]

# category, slug, name, price, tagline, para, specs
PRINTING = [
    ("business-card-printing", "Business Card Printing", "From \u20b91,050 / 500 cards",
     "Cards that earn a second look",
     ["We print business cards on 300\u2013600 GSM imported art board with velvet-matt lamination as standard \u2014 heavy enough to feel deliberate, thin enough for a wallet.",
      "Add gold or rose-gold foil, raised spot UV, coloured edge painting or a 600 GSM sandwich core when you want the card to do the talking before you do."],
     [["Standard size", "90 \u00d7 54 mm (custom available)"], ["Board", "300 / 350 / 600 GSM art board"],
      ["Finishes", "Matt, velvet, spot UV, foil, edge paint"], ["Turnaround", "24\u201372 hours"]]),
    ("letterhead-printing", "Letterhead Printing", "From \u20b92.30 / sheet",
     "Stationery that looks like your brand",
     ["A4 and A5 letterheads on imported bond, maplitho and textured stocks with pin-sharp logo reproduction and colours that hold from the first sheet to the last.",
      "Single or multi-colour, with optional watermark, foil or emboss for legal, medical and corporate offices that care how their paper feels."],
     [["Sizes", "A4, A5, Executive, custom"], ["Paper", "90\u2013120 GSM bond, maplitho, textured"],
      ["Finishes", "Foil, emboss, spot UV, watermark"], ["Turnaround", "48 hours from approval"]]),
    ("envelope-printing", "Envelope Printing", "From \u20b93.20 / envelope",
     "Branded before it's opened",
     ["Cloth-lined, window and standard envelopes printed with your logo, address and GSTIN in crisp registration \u2014 from a box of 100 to runs of a lakh.",
      "Available in white wove, brown kraft and coloured stocks, with peel-seal or gum options."],
     [["Sizes", "9\u00d74, 10\u00d74.5, A4, DL, custom"], ["Stock", "80\u2013120 GSM wove / kraft"],
      ["Options", "Window, cloth-lined, peel-seal"], ["Turnaround", "3\u20135 working days"]]),
    ("id-card-printing", "ID Card Printing", "From \u20b918 / card",
     "PVC cards that last the year",
     ["Full-colour PVC ID cards for offices, schools and events \u2014 printed both sides with QR or barcode, then laminated for daily handling.",
      "Bulk data-merge from your Excel sheet so a thousand named cards come out in the right order, ready to issue."],
     [["Material", "760-micron PVC"], ["Print", "Edge-to-edge, front & back"],
      ["Extras", "QR / barcode, magnetic strip"], ["Turnaround", "2\u20134 working days"]]),
    ("lanyard-printing", "Lanyard Printing", "From \u20b924 / piece",
     "Necks up, brand on show",
     ["Dye-sublimation lanyards printed edge-to-edge in your colours, with metal hooks, safety breakaways and card holders to match your ID run.",
      "Great for conferences, factories and campuses \u2014 order lanyards and ID cards together and we register the colours across both."],
     [["Width", "15 / 20 / 25 mm"], ["Print", "Full-colour dye-sublimation"],
      ["Fittings", "J-hook, swivel, breakaway"], ["Turnaround", "4\u20136 working days"]]),
    ("book-printing", "Book Printing", "From \u20b942 / copy",
     "From manuscript to shelf",
     ["Perfect-bound and hardcover books printed on cream or white text stock with a laminated cover \u2014 short runs for authors, long runs for publishers.",
      "We handle spine calculation, cover wrap and ISBN barcode placement so your file is press-ready without the guesswork."],
     [["Binding", "Perfect, hardcase, section-sewn"], ["Text", "70\u201390 GSM cream / white"],
      ["Cover", "250\u2013300 GSM with lamination"], ["Turnaround", "6\u201310 working days"]]),
    ("flyer-printing", "Flyer Printing", "From \u20b90.80 / flyer",
     "Bulk reach, clean colour",
     ["Single and double-sided flyers from 100 to 1,00,000 copies with even colour right across the run \u2014 no muddy shadows on copy five thousand.",
      "Gloss or matt art paper, cut to A6, A5, A4 or a custom size, delivered shrink-wrapped in counted bundles."],
     [["Sizes", "A6, A5, A4, DL, custom"], ["Paper", "80\u2013170 GSM art / maplitho"],
      ["Options", "Single / double sided, gloss / matt"], ["Turnaround", "24 hours, standard sizes"]]),
    ("brochure-printing", "Brochure Printing", "From \u20b916 / brochure",
     "Bound stories about your product",
     ["Bi-fold, tri-fold and Z-fold brochures with precise creasing that folds clean every time, printed on 130\u2013300 GSM art stock.",
      "Matt or gloss lamination on the cover, spot UV on request, and colour sampled during the run for catalogue-grade consistency."],
     [["Formats", "Bi-fold, tri-fold, Z-fold"], ["Paper", "130\u2013300 GSM art paper"],
      ["Finish", "Matt / gloss lamination, spot UV"], ["Turnaround", "3\u20135 working days"]]),
    ("booklet-printing", "Booklet Printing", "From \u20b928 / booklet",
     "Saddle-stitched and sharp",
     ["Saddle-stitched and wiro booklets for annual reports, product guides and event programmes \u2014 trimmed square with a laminated cover.",
      "Page counts in multiples of four, with numbering, section dividers and a proof before the full run."],
     [["Binding", "Saddle-stitch, wiro"], ["Pages", "8 to 96 (\u00d74)"],
      ["Cover", "250 GSM with lamination"], ["Turnaround", "4\u20137 working days"]]),
    ("bill-book-printing", "Bill Book Printing", "From \u20b985 / book",
     "Carbonless books that add up",
     ["Two- and three-copy NCR bill books, invoices and delivery challans numbered in sequence and padded or bound to your format.",
      "GST-ready layouts with your logo, terms and bank details \u2014 printed so every carbon copy stays legible."],
     [["Copies", "Duplicate / triplicate NCR"], ["Size", "1/3, 1/4, 1/6, custom"],
      ["Binding", "Pad, gum, spiral, numbered"], ["Turnaround", "3\u20135 working days"]]),
    ("certificate-printing", "Certificate Printing", "From \u20b96 / certificate",
     "Achievements worth framing",
     ["Certificates on textured 250\u2013300 GSM stock with optional gold foil borders, seals and serial numbering for schools, academies and companies.",
      "Bulk name personalisation from your list, printed and ready to sign or hand out on the day."],
     [["Stock", "250\u2013300 GSM textured"], ["Extras", "Gold foil, seal, serial number"],
      ["Personalisation", "Bulk name merge"], ["Turnaround", "2\u20134 working days"]]),
    ("poster-printing", "Poster Printing", "From \u20b930 / sq ft",
     "Big, bright and photo-sharp",
     ["Indoor and outdoor posters at true photo resolution \u2014 from A3 shop posters to ten-foot event backdrops on flex, vinyl or photo paper.",
      "Fade-resistant inks for outdoor life, with mounting and eyelets on request."],
     [["Media", "Art paper, flex, vinyl, photo"], ["Max width", "10 ft seamless"],
      ["Extras", "Mounting, eyelets, lamination"], ["Turnaround", "Same day for standard sizes"]]),
    ("stickers-printing", "Stickers Printing", "From \u20b92.40 / sticker",
     "Peel, stick, get seen",
     ["Die-cut, kiss-cut and sheet stickers on paper, vinyl and transparent film \u2014 waterproof options for bottles, boxes and outdoor use.",
      "Any shape you can draw, cut to the outline, supplied on sheets or rolls."],
     [["Material", "Paper, vinyl, transparent, metallic"], ["Cut", "Die-cut, kiss-cut, sheet"],
      ["Finish", "Gloss, matt, waterproof"], ["Turnaround", "3\u20135 working days"]]),
    ("product-label-printing", "Product Label Printing", "From \u20b91.90 / label",
     "Shelf-ready, compliance-ready",
     ["Roll and sheet labels for food, beverage and cosmetics \u2014 printed with your artwork, batch codes and FSSAI details in registration.",
      "Laminated or varnished for fridge and freezer life, die-cut to your container shape."],
     [["Format", "Roll, sheet, die-cut"], ["Material", "Chromo, vinyl, transparent"],
      ["Compliance", "FSSAI / statutory ready"], ["Turnaround", "4\u20136 working days"]]),
    ("mug-printing", "Mug Printing", "From \u20b9149 / mug",
     "Coffee with your logo on it",
     ["Sublimation and photo mugs \u2014 white, magic colour-change, and inner-coloured \u2014 printed with logos, photos and messages that survive the dishwasher.",
      "Ideal for gifting, onboarding kits and event giveaways, from one mug to a thousand."],
     [["Types", "White, magic, inner-colour, patch"], ["Print", "Full-wrap sublimation"],
      ["MOQ", "1 piece"], ["Turnaround", "2\u20134 working days"]]),
    ("water-bottle-printing", "Water Bottle Printing", "From \u20b9179 / bottle",
     "Hydration, branded",
     ["Steel and tritan bottles printed or laser-engraved with your logo \u2014 corporate gifting that stays on the desk long after the event.",
      "UV-print for full colour or engraving for a premium, wear-proof mark."],
     [["Material", "Steel, tritan, aluminium"], ["Method", "UV print / laser engrave"],
      ["MOQ", "10 pieces"], ["Turnaround", "4\u20137 working days"]]),
    ("keychain-printing", "Keychain Printing", "From \u20b939 / piece",
     "Pocket-sized brand recall",
     ["Acrylic, metal and leatherette keychains printed or engraved with logos, names and QR codes \u2014 a low-cost giveaway that keeps working.",
      "Custom shapes for showrooms, resorts and events, supplied bagged and ready to hand out."],
     [["Material", "Acrylic, metal, leatherette, rubber"], ["Method", "UV print / engrave / dome"],
      ["Shape", "Standard or custom die"], ["Turnaround", "4\u20136 working days"]]),
    ("wedding-card-printing", "Wedding Card Printing", "From \u20b924 / card",
     "The first impression of the big day",
     ["Traditional and contemporary wedding invitations \u2014 foil, laser-cut, box and scroll styles on premium boards, with matching envelopes and inserts.",
      "Tamil and English typesetting, muhurtham details checked twice, and a physical sample before the full run."],
     [["Styles", "Foil, laser-cut, box, scroll"], ["Board", "250\u2013400 GSM premium"],
      ["Extras", "Envelopes, inserts, tags, RSVP"], ["Turnaround", "5\u20139 working days"]]),
    ("cd-sticker-printing", "CD Sticker Printing", "From \u20b94.50 / sticker",
     "Round labels, dead-centre",
     ["Circular CD and DVD face stickers printed with a centred hole punch and matt or gloss finish \u2014 for studios, software and audio releases.",
      "Supplied on sheets, aligned to fit standard disc applicators."],
     [["Size", "117 mm disc, 41 mm centre"], ["Material", "Gloss / matt sticker paper"],
      ["Cut", "Pre-punched circular"], ["Turnaround", "3\u20135 working days"]]),
]

DESIGN = [
    ("business-card-design", "Business Card Design", "From \u20b9499",
     "First impressions, engineered",
     ["Two original card concepts built from your logo and role \u2014 typographic, minimal or bold, in print-ready CMYK with bleed and crop marks set correctly.",
      "One round of revisions included, plus source files so your card can grow into a full identity later."],
     [["Concepts", "2 unique designs"], ["Files", "Print-ready PDF + source"],
      ["Sides", "Single or double"], ["Turnaround", "24\u201348 hours"]]),
    ("letterhead-design", "Letterhead Design", "From \u20b9399",
     "Corporate identity on every page",
     ["Clean, functional letterhead layouts that carry your logo, contact block and brand colours without crowding the writing space.",
      "Delivered as print PDF plus an editable Word template your team can type into every day."],
     [["Layout", "Modern, minimal, classic"], ["Files", "PDF, AI, Word template"],
      ["Size", "A4 / US Letter"], ["Turnaround", "24 hours"]]),
    ("envelope-design", "Envelope Design", "From \u20b9299",
     "Brand the mail itself",
     ["Envelope artwork that positions your logo, return address and window correctly for the size you post \u2014 no misaligned surprises at print.",
      "Supplied as press-ready CMYK files for any standard or custom envelope."],
     [["Sizes", "9\u00d74, DL, A4, custom"], ["Includes", "Logo + contact integration"],
      ["Output", "Print-ready CMYK"], ["Turnaround", "24 hours"]]),
    ("id-card-design", "ID Card Design", "From \u20b9199 / design",
     "Smart, secure identity",
     ["Front-and-back ID card layouts for offices, schools and events with space for photo, QR, blood group and emergency contact.",
      "A reusable template so future joiners drop into the same clean design."],
     [["Style", "Corporate / campus / event"], ["Layout", "Front & back"],
      ["Data", "QR / barcode ready"], ["Turnaround", "24\u201348 hours"]]),
    ("flyer-design", "Flyer Design", "From \u20b9799",
     "Attention that converts",
     ["High-impact single-page flyers with a clear hierarchy \u2014 offer, proof, call to action \u2014 sized for handout, insert or WhatsApp forward.",
      "Print and web-optimised versions so the same campaign works on paper and on a phone."],
     [["Focus", "High-conversion layout"], ["Output", "Print + web optimised"],
      ["Size", "A5, A4, custom"], ["Turnaround", "2 days"]]),
    ("certificate-design", "Certificate Design", "From \u20b9599",
     "Honour, elegantly set",
     ["Certificate layouts with custom borders, motifs and seal placement for schools, workshops and corporate recognition.",
      "Editable vector so names, dates and signatories change without a redesign."],
     [["Style", "Classic / modern / sporty"], ["Detail", "Custom borders & motifs"],
      ["File", "Editable vector"], ["Turnaround", "24\u201348 hours"]]),
    ("brochure-design", "Brochure Design", "From \u20b91,499",
     "Your story, in order",
     ["Multi-panel brochure layouts that organise your product or service into a sequence a reader can follow \u2014 built to fold clean at print.",
      "Bi-fold, tri-fold or booklet, with image treatment and iconography to match your brand."],
     [["Format", "Bi-fold / tri-fold / booklet"], ["Pages", "From 4 pages"],
      ["Quality", "Print-ready high-res"], ["Turnaround", "3\u20135 days"]]),
    ("bill-book-design", "Bill Book & Invoice Design", "From \u20b9299",
     "Billing that looks the part",
     ["Branded, GST-ready invoice and bill-book layouts with your logo, terms, HSN columns and bank details in a format your NCR printer can run.",
      "Optimised for carbonless copies so every duplicate stays readable."],
     [["Items", "Invoice, voucher, receipt"], ["Layout", "Carbonless / NCR ready"],
      ["Size", "1/3, 1/4, custom"], ["Turnaround", "24 hours"]]),
    ("book-design", "Book & Cover Design", "From \u20b92,999",
     "Design that demands a read",
     ["Cover and interior layout for authors and publishers \u2014 typographic covers, calculated spine and clean, readable body pages.",
      "Files formatted for Amazon KDP and local press, with an ebook-ready export on request."],
     [["Service", "Cover + interior layout"], ["Spine", "Calculated to page count"],
      ["Formats", "KDP / local print ready"], ["Turnaround", "7\u201310 days"]]),
    ("catalogue-design", "Catalogue Design", "From \u20b91,999",
     "Your whole range, browsable",
     ["Product and service catalogues with an index, categories and spec tables so customers can find and compare without help.",
      "Delivered as print PDF and an interactive PDF with clickable navigation."],
     [["Type", "Product / service catalogue"], ["Features", "Index, categories, spec tables"],
      ["Files", "Print + interactive PDF"], ["Turnaround", "5\u201310 days"]]),
    ("standee-design", "Standee & Banner Design", "From \u20b9599",
     "Big-format, high-impact",
     ["Roll-up standee and banner artwork built at large-format resolution so text stays crisp from across the hall.",
      "Exhibition, storefront and event sizes, with a layout that reads in three seconds."],
     [["Size", "6\u00d73 ft, 6\u00d72.5 ft, custom"], ["Visuals", "High-res vector / raster"],
      ["Output", "TIFF / PDF for large format"], ["Turnaround", "24\u201348 hours"]]),
    ("product-label-design", "Product Label Design", "From \u20b9899",
     "Packaging that sells itself",
     ["Label artwork for food, beverage and cosmetics \u2014 appetising, on-brand and built around statutory and FSSAI requirements from the start.",
      "Die-cut-ready vector so the printer trims exactly to your container."],
     [["Industry", "FMCG, cosmetics, food & bev"], ["Compliance", "FSSAI / statutory ready"],
      ["Format", "Die-cut ready vector"], ["Turnaround", "3\u20135 days"]]),
]
